# Generated by Django 2.2.4 on 2019-08-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_text',
            field=models.TextField(max_length=99999),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(max_length=80),
        ),
    ]
