# Generated by Django 2.2.4 on 2019-08-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20190808_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_picture',
            field=models.ImageField(default='static/ubuntu_orange.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_picture',
            field=models.ImageField(default='static/ubuntu_orange.png', upload_to=''),
        ),
    ]
