# Generated by Django 2.2.4 on 2019-08-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20190808_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_picture',
            field=models.ImageField(default='images/ubuntu_orange.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_picture',
            field=models.ImageField(default='images/ubuntu_orange.png', upload_to=''),
        ),
    ]
